### ISSUE TITLE
`TypeError: Cannot read property 'get' of undefined`

### ISSUE THREAD

**Issue by kejadlen** [SmartThingsCommunity/smartapp-sdk-nodejs#95]
**Describe the bug**

With 1.5.0, I'm getting `TypeError: Cannot read property 'get' of undefined` when configuring the app without a context store.

**To Reproduce**
1. Run the app with a configuration specified, but no context store.
2. Try configuring an installed automation or installing the automation.

**Expected behavior**
The configuration screen is displayed.

**Actual behavior**
We send a 500 with the error above and the following stack trace:

```
2019-07-23T03:23:29.787Z error: TypeError: Cannot read property 'get' of undefined
    at EndpointContext.retrieveTokens (.../node_modules/@smartthings/smartapp/lib/util/endpoint-context.js:104:40)                                                            
    at SmartApp._handleCallback (.../node_modules/@smartthings/smartapp/lib/smart-app.js:598:22)                                                                              
    at SmartApp.handleHttpCallback (.../node_modules/@smartthings/smartapp/lib/smart-app.js:505:16)                                                                           
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
2019-07-23T03:23:29.788Z debug: RESPONSE: {
  "statusCode": 500,
  "message": "Server error: 'TypeError: Cannot read property 'get' of undefined'"
```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Node engine: 12.4.0

**Additional context**
N/A

**Comment by erodewald** [comment]
Thanks for submitting an issue @kejadlen, this was fixed in PR #96 which was deployed as 1.5.1
